### ISSUE TITLE
Crash when removing "Override" of sensitivity in PrivacyProfileMapFragment

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#20]
```
FATAL EXCEPTION: main
Process: tinygsn.gui.android, PID: 16950
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.model.Polygon.remove()' on a null object reference
at org.epfl.locationprivacy.privacyprofile.activities.PrivacyProfileMapFragment$1.onClick(PrivacyProfileMapFragment.java:102)
at android.view.View.performClick(View.java:4780)
at android.widget.CompoundButton.performClick(CompoundButton.java:120)
at android.view.View$PerformClick.run(View.java:19866)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by AblionGE** [comment]
The problem was a conversion from long to int when reading from DB in `findSensitiveGridCells()`
