### ISSUE TITLE
File not found when test semantic sensitivities

### ISSUE THREAD

**Issue by AblionGE** [AblionGE/LocPrivLib#3]
Example of syserr :

``````
10-20 15:12:06.047 6941-6941/org.epfl.locationprivacy W/System.err: java.io.FileNotFoundException: sdcard/LocationPrivacyLibrary/1445346721384/1445346723919/AdaptiveProtection.txt: open failed: ENOENT (No such file or directory)
10-20 15:12:06.048 6941-6941/org.epfl.locationprivacy W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
10-20 15:12:06.048 6941-6941/org.epfl.locationprivacy W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
10-20 15:12:06.048 6941-6941/org.epfl.locationprivacy W/System.err:     at java.io.FileWriter.<init>(FileWriter.java:58)
10-20 15:12:06.048 6941-6941/org.epfl.locationprivacy W/System.err:     at org.epfl.locationprivacy.util.Utils.appendLog(Utils.java:391)
10-20 15:12:06.048 6941-6941/org.epfl.locationprivacy W/System.err:     at org.epfl.locationprivacy.adaptiveprotection.AdaptiveProtection.log(AdaptiveProtection.java:240)
10-20 15:12:06.049 6941-6941/org.epfl.locationprivacy W/System.err:     at org.epfl.locationprivacy.adaptiveprotection.AdaptiveProtection.getObfuscationLocation(AdaptiveProtection.java:219)
10-20 15:12:06.049 6941-6941/org.epfl.locationprivacy W/System.err:     at org.epfl.locationprivacy.thirdpartyemulator.ThirdPartyActivity.emulateThirdParty(ThirdPartyActivity.java:134)
10-20 15:12:06.049 6941-6941/org.epfl.locationprivacy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-20 15:12:06.049 6941-6941/org.epfl.locationprivacy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-20 15:12:06.049 6941-6941/org.epfl.locationprivacy W/System.err:     at android.view.View$1.onClick(View.java:4015)
10-20 15:12:06.049 6941-6941/org.epfl.locationprivacy W/System.err:     at android.view.View.performClick(View.java:4780)
10-20 15:12:06.049 6941-6941/org.epfl.locationprivacy W/System.err:     at android.view.View$PerformClick.run(View.java:19866)
10-20 15:12:06.049 6941-6941/org.epfl.locationprivacy W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
10-20 15:12:06.050 6941-6941/org.epfl.locationprivacy W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-20 15:12:06.050 6941-6941/org.epfl.locationprivacy W/System.err:     at android.os.Looper.loop(Looper.java:135)
10-20 15:12:06.050 6941-6941/org.epfl.locationprivacy W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
10-20 15:12:06.050 6941-6941/org.epfl.locationprivacy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-20 15:12:06.050 6941-6941/org.epfl.locationprivacy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-20 15:12:06.050 6941-6941/org.epfl.locationprivacy W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-20 15:12:06.050 6941-6941/org.epfl.locationprivacy W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
10-20 15:12:06.051 6941-6941/org.epfl.locationprivacy W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
10-20 15:12:06.051 6941-6941/org.epfl.locationprivacy W/System.err:     at libcore.io.Posix.open(Native Method)
10-20 15:12:06.051 6941-6941/org.epfl.locationprivacy W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-20 15:12:06.052 6941-6941/org.epfl.locationprivacy W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:442)
10-20 15:12:06.052 6941-6941/org.epfl.locationprivacy W/System.err:     ... 19 more
10-20 15:12:06.052 6941-6941/org.epfl.locationprivacy D/AdaptiveProtection: Total Adaptive Protection Time without logging : 1528 ms
10-20 15:12:06.061 6941-6941/org.epfl.locationprivacy W/System.err: java.io.IOException: open failed: ENOENT (No such file or directory)
10-20 15:12:06.062 6941-6941/org.epfl.locationprivacy W/System.err:     at java.io.File.createNewFile(File.java:941)
10-20 15:12:06.062 6941-6941/org.epfl.locationprivacy W/System.err:     at org.epfl.locationprivacy.util.Utils.appendLog(Utils.java:383)
10-20 15:12:06.062 6941-6941/org.epfl.locationprivacy W/System.err:     at org.epfl.locationprivacy.adaptiveprotection.AdaptiveProtection.log(AdaptiveProtection.java:240)
10-20 15:12:06.062 6941-6941/org.epfl.locationprivacy W/System.err:     at org.epfl.locationprivacy.adaptiveprotection.AdaptiveProtection.getObfuscationLocation(AdaptiveProtection.java:220)
10-20 15:12:06.062 6941-6941/org.epfl.locationprivacy W/System.err:     at org.epfl.locationprivacy.thirdpartyemulator.ThirdPartyActivity.emulateThirdParty(ThirdPartyActivity.java:134)
10-20 15:12:06.062 6941-6941/org.epfl.locationprivacy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-20 15:12:06.063 6941-6941/org.epfl.locationprivacy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-20 15:12:06.063 6941-6941/org.epfl.locationprivacy W/System.err:     at android.view.View$1.onClick(View.java:4015)
10-20 15:12:06.063 6941-6941/org.epfl.locationprivacy W/System.err:     at android.view.View.performClick(View.java:4780)
10-20 15:12:06.063 6941-6941/org.epfl.locationprivacy W/System.err:     at android.view.View$PerformClick.run(View.java:19866)
10-20 15:12:06.063 6941-6941/org.epfl.locationprivacy W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
10-20 15:12:06.063 6941-6941/org.epfl.locationprivacy W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-20 15:12:06.063 6941-6941/org.epfl.locationprivacy W/System.err:     at android.os.Looper.loop(Looper.java:135)
10-20 15:12:06.064 6941-6941/org.epfl.locationprivacy W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
10-20 15:12:06.064 6941-6941/org.epfl.locationprivacy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-20 15:12:06.064 6941-6941/org.epfl.locationprivacy W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-20 15:12:06.064 6941-6941/org.epfl.locationprivacy W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-20 15:12:06.064 6941-6941/org.epfl.locationprivacy W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
10-20 15:12:06.064 6941-6941/org.epfl.locationprivacy W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
10-20 15:12:06.065 6941-6941/org.epfl.locationprivacy W/System.err:     at libcore.io.Posix.open(Native Method)
10-20 15:12:06.067 6941-6941/org.epfl.locationprivacy W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-20 15:12:06.067 6941-6941/org.epfl.locationprivacy W/System.err:     at java.io.File.createNewFile(File.java:934)
10-20 15:12:06.068 6941-6941/org.epfl.locationprivacy W/System.err:     ... 17 more```
``````

**Comment by AblionGE** [comment]
Same for `Test Location Sensitivities`

**Comment by AblionGE** [comment]
This is because of https://github.com/AblionGE/LocPrivLib/blob/master/app/src/main/java/org/epfl/locationprivacy/util/Utils.java#L362

**Comment by berkeragir** [comment]
Yes. This parameter considers the existence of an 'sdcard' even if it is just logical (i.e., on some phones I think the internal storage is mounted as an sdcard as well event if there is no sdcard in reality). This is part of the logging system, we need to design this in a better way.

**Comment by AblionGE** [comment]
I'm trying to fix it

**Comment by AblionGE** [comment]
fixed
